=== korea-doko/Evolve/Evolve Project/Assets/Resources/TextAsset/Selection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Selection" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Selection">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="CardID" index-key="CardID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="GivenID" index-key="GivenID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="NextCardID" index-key="NextCardID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="ynvHDEPuwkqwNwQ/ZXXO4A==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADKe8cMQ+7CSrA3BD9ldc7gAAAAAF5HkoQT7ORAAAAAAAAAAABTAGUA
bABlAGMAdABpAG8AbgAAAAAAAACOGNZFvP5JRY7lY6KSzwcXBwAAAMp7xwxD7sJK
sDcEP2V1zuBJAEQAAAAAAAAA+loLYYP6BUioXT1EHhjITQcAAADKe8cMQ+7CSrA3
BD9ldc7gRwBpAHYAZQBuAEkARAAAAAAAAAAh/tL0qxHlSYoTzSaWICurBwAAAMp7
xwxD7sJKsDcEP2V1zuBEAGUAcwBjAAAAAAAAAH/aKS0vd+ZKuQBJ75meQBYHAAAA
ynvHDEPuwkqwNwQ/ZXXO4EQAZQBsAHQAYQBEAGEAbQBhAGcAZQAAAAAAAAA9yCjK
KUx/SpOIakxeLpPQBwAAAMp7xwxD7sJKsDcEP2V1zuBEAGUAbAB0AGEATABpAGYA
ZQAAAAAAAAAA/1zAaMhzS5xrWqGWwulZBwAAAMp7xwxD7sJKsDcEP2V1zuBEAGUA
bAB0AGEARQB4AHAAAAAAAAAAKB5q5Kahx0q27N0w36fp7gcAAADKe8cMQ+7CSrA3
BD9ldc7gRABlAGwAdABhAEgAdQBuAGcAcgB5AAAAAAAAAA2N+n/pspNHgHryOADM
f8AHAAAAynvHDEPuwkqwNwQ/ZXXO4EQAZQBsAHQAYQBNAGEAZwBpAGMAUABvAHcA
ZQByAAAAAAAAAOF4Q+8ktvtNmSsdc6q4JeoHAAAAynvHDEPuwkqwNwQ/ZXXO4EMA
YQByAGQASQBEAAAAAAAAAFJeFFljAShDjKxbJ2U5aYoHAAAAynvHDEPuwkqwNwQ/
ZXXO4E4AZQB4AHQAQwBhAHIAZABJAEQAAAAAAAAAB+Wk7fxewkWoMecKj6KW6wcA
AADKe8cMQ+7CSrA3BD9ldc7gTgBlAHgAdABOAFAAQwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="jhjWRbz+SUWO5WOiks8HFw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="690"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GivenID" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="+loLYYP6BUioXT1EHhjITQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1725"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Desc" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="If7S9KsR5UmKE80mliArqw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3540"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DeltaDamage" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="f9opLS935kq5AEnvmZ5AFg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1320"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DeltaLife" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="PcgoyilMf0qTiGpMXi6T0A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1530"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DeltaExp" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="AP9cwGjIc0uca1qhlsLpWQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1365"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DeltaHungry" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="KB5q5Kahx0q27N0w36fp7g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1155"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DeltaMagicPower" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="DY36f+myk0eAevI4AMx/wA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2175"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CardID" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4XhD7yS2+02ZKx1zqrgl6g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="NextCardID" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Ul4UWWMBKEOMrFsnZTlpig==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="NextNPC" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="B+Wk7fxewkWoMecKj6KW6w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="11"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Value List"/>
<od:fieldProperty name="RowSource" type="12" value="&quot;None&quot;;&quot;Player&quot;;&quot;God&quot;;&quot;GoblinChildMinder&quot;;&quot;GoblinWarrior&quot;;&quot;GoblinVillage&quot;"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Evolve/Evolve Project/Assets/Resources/TextAsset/Selection.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Selection.xsd" generated="2017-04-15T14:37:54">
<Selection>
<ID>1</ID>
<GivenID>101</GivenID>
<SelectionName>숲으로 이동</SelectionName>
<Desc>숲으로 간다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>2</ID>
<GivenID>102</GivenID>
<SelectionName>동쪽으로 이동</SelectionName>
<Desc>동쪽으로이동</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>3</ID>
<GivenID>103</GivenID>
<SelectionName>서쪽으로 이동</SelectionName>
<Desc>서쪽으로이동</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>4</ID>
<GivenID>104</GivenID>
<SelectionName>남쪽으로 이동</SelectionName>
<Desc>남쪽으로 이동</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>5</ID>
<GivenID>105</GivenID>
<SelectionName>북쪽으로 이동</SelectionName>
<Desc>북쪽으로 이동</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>6</ID>
<GivenID>106</GivenID>
<SelectionName>강으로 이동</SelectionName>
<Desc>강으로 이동</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>7</ID>
<GivenID>107</GivenID>
<SelectionName>고대 사원으로 이동</SelectionName>
<Desc>고대 사원으로 간다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>8</ID>
<GivenID>108</GivenID>
<SelectionName>던전으로 이동</SelectionName>
<Desc>던전 안으로 간다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>9</ID>
<GivenID>109</GivenID>
<SelectionName>동굴로 이동</SelectionName>
<Desc>동굴 속으로 들어간다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>10</ID>
<GivenID>110</GivenID>
<SelectionName>산으로 이동</SelectionName>
<Desc>산으로 간다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>11</ID>
<GivenID>201</GivenID>
<SelectionName>잠을 잔다</SelectionName>
<Desc>잠을 잔다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>3</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>12</ID>
<GivenID>202</GivenID>
<SelectionName>밥을 먹는다</SelectionName>
<Desc>밥을 먹는다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>1</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>-3</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>13</ID>
<GivenID>203</GivenID>
<SelectionName>운동한다</SelectionName>
<Desc>운동한다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>1</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
</Selection>
<Selection>
<ID>14</ID>
<GivenID>204</GivenID>
<SelectionName>마법 연습</SelectionName>
<Desc>마법을 연습한다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>1</DeltaLife>
<DeltaExp>1</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>3</DeltaMagicPower>
</Selection>
<Selection>
<ID>15</ID>
<GivenID>205</GivenID>
<SelectionName>명상</SelectionName>
<Desc>명상하기</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>1</DeltaLife>
<DeltaExp>3</DeltaExp>
<DeltaHungry>1</DeltaHungry>
<DeltaMagicPower>1</DeltaMagicPower>
</Selection>
</dataroot>

=== korea-doko/Evolve/Evolve Project/Assets/Resources/TextAssets/Selection.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Selection.xsd" generated="2017-04-24T11:07:18">
<Selection>
<ID>1</ID>
<GivenID>1</GivenID>
<Desc>으… 머리야 당신은 누구지</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>1</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>16</ID>
<GivenID>2</GivenID>
<Desc>나는.. 죽은 것인가?</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>1</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>17</ID>
<GivenID>3</GivenID>
<Desc>신? 그런게 있을리 없잖아?</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>2</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>18</ID>
<GivenID>4</GivenID>
<Desc>…</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>2</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>19</ID>
<GivenID>5</GivenID>
<Desc>다른 세계?</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>3</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>20</ID>
<GivenID>6</GivenID>
<Desc>잠시.. 다른 기회라니?</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>3</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>21</ID>
<GivenID>7</GivenID>
<Desc>새로운 삶이라..좋아!</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>4</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>22</ID>
<GivenID>8</GivenID>
<Desc>그래 어디에서 살아가는거지?</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>4</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>23</ID>
<GivenID>9</GivenID>
<Desc>이 세계라니?</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>5</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>24</ID>
<GivenID>10</GivenID>
<Desc>마법과 몬스터?</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>5</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>25</ID>
<GivenID>11</GivenID>
<Desc>위험한 곳 아니야?</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>5</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>26</ID>
<GivenID>12</GivenID>
<Desc>질문?</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>6</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>27</ID>
<GivenID>13</GivenID>
<Desc>좋아. 뭐든 물어봐</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>6</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>28</ID>
<GivenID>14</GivenID>
<Desc>고블, 좋다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>10</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>29</ID>
<GivenID>15</GivenID>
<Desc>고블, 싫다</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>10</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>30</ID>
<GivenID>16</GivenID>
<Desc>고블, 과일 많이 먹고 싶다!</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>10</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>32</ID>
<GivenID>18</GivenID>
<Desc>고블, 나 아직 잘 모르겠다.</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>11</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>33</ID>
<GivenID>19</GivenID>
<Desc>고블, 난…</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>11</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>35</ID>
<GivenID>21</GivenID>
<Desc>싫다. 고블!</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>12</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>36</ID>
<GivenID>22</GivenID>
<Desc>고블린 보모를 만난다.</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>13</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>GoblinChildMinder</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>37</ID>
<GivenID>23</GivenID>
<Desc>마법 연습을 한다.</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>13</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>38</ID>
<GivenID>24</GivenID>
<Desc>숨어서 음식을 훔친다.</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>13</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>39</ID>
<GivenID>25</GivenID>
<Desc>알겠어</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>7</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>31</ID>
<GivenID>17</GivenID>
<Desc>고블, 나 강한 전사가 될꺼다!</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>11</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
<Selection>
<ID>34</ID>
<GivenID>20</GivenID>
<Desc>여기 있다. 고블!</Desc>
<DeltaDamage>0</DeltaDamage>
<DeltaLife>0</DeltaLife>
<DeltaExp>0</DeltaExp>
<DeltaHungry>0</DeltaHungry>
<DeltaMagicPower>0</DeltaMagicPower>
<CardID>12</CardID>
<NextCardID>-1</NextCardID>
<NextNPC>None</NextNPC>
<DeltaVirtue>0</DeltaVirtue>
</Selection>
</dataroot>
