=== korea-doko/Evolve/Evolve Project/Assets/Resources/TextAssets/CardTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="CardTable" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="CardTable">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="4eJ9VtmXPEGjBYwkEDFx6g==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADh4n1W2Zc8QaMFjCQQMXHqAAAAAGWbkF1Q7uRAAAAAAAAAAABDAGEA
cgBkAFQAYQBiAGwAZQAAAAAAAACqLzYc1YQeRY0y1evoeoVMBwAAAOHifVbZlzxB
owWMJBAxcepJAEQAAAAAAAAAfNG/Kw5RF0yUtXYvp/pm1gcAAADh4n1W2Zc8QaMF
jCQQMXHqRABlAHMAYwAAAAAAAADsYFZQE+2dQIudqTLMqcO0AAAAABMuggpQ7uRA
AAAAAAAAAABOAFAAQwBOAGEAbQBlAFQAYQBiAGwAZQAAAAAAAACzxKOBEeXxSLJ1
av6yjte2BwAAAOxgVlAT7Z1Ai52pMsypw7RJAEQAAAAAAAAA91jj1GrftkKkOr54
XW0cYQcAAADsYFZQE+2dQIudqTLMqcO0TgBQAEMATgBhAG0AZQAAAAAAAABZphp6
PgE0RbI0ZF+CnhWFBwAAAOHifVbZlzxBowWMJBAxcepOAGUAeAB0AE4AUABDAAAA
AAAAAMGz2L2W3SJDgTWJ9kuvayAAAAAArhpx3i/u5EAAAAAAAAAAAEMAYQByAGQA
TgBhAG0AZQBUAGEAYgBsAGUAAAAAAAAAx4R9Govs7kaQa0hhKHfGmQcAAADBs9i9
lt0iQ4E1ifZLr2sgSQBEAAAAAAAAAGi+xlQb251FlD2l4Ql8cowHAAAAwbPYvZbd
IkOBNYn2S69rIEMAYQByAGQATgBhAG0AZQAAAAAAAACQ3H78kWSWQal2R6ogXbZ2
BwAAAOHifVbZlzxBowWMJBAxcepDAGEAcgBkAE4AYQBtAGUAAAAAAAAAgrw8oQ9n
vkuPya2kuxezgQcAAADh4n1W2Zc8QaMFjCQQMXHqTgBlAHgAdABDAGEAcgBkAE4A
YQBtAGUAAAAAAAAABqWwXoM/Kk+VkNumBoel6AcAAADh4n1W2Zc8QaMFjCQQMXHq
TgBQAEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAA
AAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="qi82HNWEHkWNMtXr6HqFTA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1200"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Desc" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="fNG/Kw5RF0yUtXYvp/pm1g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="5130"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="NextNPC" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="WaYaej4BNEWyNGRfgp4VhQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1815"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [NPCNameTable].[ID], [NPCNameTable].[NPCName] FROM NPCNameTable; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="CardName" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="kNx+/JFklkGpdkeqIF22dg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1530"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [CardNameTable].[ID], [CardNameTable].[CardName] FROM CardNameTable; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="NextCardName" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="grw8oQ9nvkuPya2kuxezgQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1710"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [CardNameTable].[ID], [CardNameTable].[CardName] FROM CardNameTable; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="NPC" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="BqWwXoM/Kk+VkNumBoel6A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [NPCNameTable].[ID], [NPCNameTable].[NPCName] FROM NPCNameTable; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Evolve/Evolve Project/Assets/Resources/TextAssets/CardTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="CardTable.xsd" generated="2017-05-10T11:59:48">
<CardTable>
<ID>1</ID>
<Desc>흠흠.. 일어났는가?</Desc>
<NPC>3</NPC>
<NextNPC>1</NextNPC>
<CardName>2</CardName>
<NextCardName>3</NextCardName>
</CardTable>
<CardTable>
<ID>2</ID>
<Desc>나는 자네들이 신이라고 부르는 존재일세</Desc>
<NPC>3</NPC>
<NextNPC>1</NextNPC>
<CardName>3</CardName>
<NextCardName>4</NextCardName>
</CardTable>
<CardTable>
<ID>3</ID>
<Desc>자네는 불의의 사고를 당해서 죽게 됐다네. 그러나 특별히 이번에 다른 세상에서 살아갈 기회를 주게 됐지</Desc>
<NPC>3</NPC>
<NextNPC>1</NextNPC>
<CardName>4</CardName>
<NextCardName>5</NextCardName>
</CardTable>
<CardTable>
<ID>4</ID>
<Desc>더 이상 지구에서 살아갈 수 없다네. 새로운 세계에서 살아가게 될 것이야.</Desc>
<NPC>3</NPC>
<NextNPC>1</NextNPC>
<CardName>5</CardName>
<NextCardName>6</NextCardName>
</CardTable>
<CardTable>
<ID>5</ID>
<Desc>어쩌다보니… 그대가 갈 수 있는 곳은 마법과 몬스터들이 있는… 흔히 자네들이 생각할 수 있는 이세계라네! 멋지지 않나?</Desc>
<NPC>3</NPC>
<NextNPC>1</NextNPC>
<CardName>6</CardName>
<NextCardName>7</NextCardName>
</CardTable>
<CardTable>
<ID>6</ID>
<Desc>뭐 세상사는 곳이 다 똑같지 않겠나? 그대의 새로운 삶을 위해서 몇 가지 질문을 하겠네!</Desc>
<NPC>3</NPC>
<NextNPC>1</NextNPC>
<CardName>7</CardName>
<NextCardName>8</NextCardName>
</CardTable>
<CardTable>
<ID>7</ID>
<Desc>좋아. 새로운 세계에서 잘 살아가게!</Desc>
<NPC>3</NPC>
<NextNPC>1</NextNPC>
<CardName>8</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>8</ID>
<Desc>배가 고픈걸?</Desc>
<NPC>2</NPC>
<NextNPC>1</NextNPC>
<CardName>9</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>9</ID>
<Desc>어디로 가야하지?</Desc>
<NPC>2</NPC>
<NextNPC>1</NextNPC>
<CardName>10</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>10</ID>
<Desc>숲으로 가서 먹을 것을 찾아와.</Desc>
<NPC>4</NPC>
<NextNPC>1</NextNPC>
<CardName>11</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>12</ID>
<Desc>먹을 것 내놔, 고블!</Desc>
<NPC>5</NPC>
<NextNPC>1</NextNPC>
<CardName>12</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>13</ID>
<Desc>(고블린 마을, 무엇을 하지?)</Desc>
<NPC>6</NPC>
<NextNPC>1</NextNPC>
<CardName>13</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>14</ID>
<Desc>(마을에 모험가 파티가 공격해왔다.)</Desc>
<NPC>6</NPC>
<NextNPC>1</NextNPC>
<CardName>14</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>15</ID>
<Desc>( 숲 ) 무엇을 할까?</Desc>
<NPC>7</NPC>
<NextNPC>1</NextNPC>
<CardName>15</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>16</ID>
<Desc>뿔 토끼를 만났다. 그러나 깊숙한 곳으로 도망쳤다.</Desc>
<NPC>7</NPC>
<NextNPC>1</NextNPC>
<CardName>16</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>17</ID>
<Desc>독이 있어보이는 작은 타란튤라를 만났다.</Desc>
<NPC>7</NPC>
<NextNPC>1</NextNPC>
<CardName>17</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>18</ID>
<Desc>처음 보는 과일이 있었다.</Desc>
<NPC>7</NPC>
<NextNPC>1</NextNPC>
<CardName>18</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>19</ID>
<Desc>깊은 숲, 그곳엔 무엇인가 있을 것 같다.</Desc>
<NPC>7</NPC>
<NextNPC>1</NextNPC>
<CardName>19</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>20</ID>
<Desc>(깊은 숲) 빛이 들어오지 않는다.</Desc>
<NPC>8</NPC>
<NextNPC>1</NextNPC>
<CardName>20</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>21</ID>
<Desc>무엇을 할까?</Desc>
<NPC>8</NPC>
<NextNPC>1</NextNPC>
<CardName>21</CardName>
<NextCardName>1</NextCardName>
</CardTable>
<CardTable>
<ID>22</ID>
<Desc>작은 빛이 보인다</Desc>
<NPC>8</NPC>
<NextNPC>1</NextNPC>
<CardName>22</CardName>
<NextCardName>1</NextCardName>
</CardTable>
</dataroot>
