=== korea-doko/Evolve/Evolve Project/Assets/Resources/TextAssets/CardNameTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="CardNameTable" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="CardNameTable">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="wbPYvZbdIkOBNYn2S69rIA==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADBs9i9lt0iQ4E1ifZLr2sgAAAAAIuxTdcv7uRAAAAAAAAAAABDAGEA
cgBkAE4AYQBtAGUAAAAAAAAAx4R9Govs7kaQa0hhKHfGmQcAAADBs9i9lt0iQ4E1
ifZLr2sgSQBEAAAAAAAAAGi+xlQb251FlD2l4Ql8cowHAAAAwbPYvZbdIkOBNYn2
S69rIEMAYQByAGQATgBhAG0AZQAAAAAAAACnID+Lbx4pTLZlBVu8ORaFBwAAAMGz
2L2W3SJDgTWJ9kuvayBDAGEAcgBkAE4AYQBtAGUARABlAHMAYwAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="x4R9Govs7kaQa0hhKHfGmQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1455"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="CardName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="aL7GVBvbnUWUPaXhCXxyjA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2700"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Value List"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CardNameDesc" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2700"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="pyA/i28eKUy2ZQVbvDkWhQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Evolve/Evolve Project/Assets/Resources/TextAssets/CardNameTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="CardNameTable.xsd" generated="2017-05-10T12:01:26">
<CardNameTable>
<ID>1</ID>
<CardName>None</CardName>
<CardNameDesc>아무것도 없을 때</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>2</ID>
<CardName>GodCard1</CardName>
<CardNameDesc>신 카드 1번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>3</ID>
<CardName>GodCard2</CardName>
<CardNameDesc>신 카드 2번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>4</ID>
<CardName>GodCard3</CardName>
<CardNameDesc>신 카드 3번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>5</ID>
<CardName>GodCard4</CardName>
<CardNameDesc>신 카드 4번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>6</ID>
<CardName>GodCard5</CardName>
<CardNameDesc>신 카드 5번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>7</ID>
<CardName>GodCard6</CardName>
<CardNameDesc>신 카드 6번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>8</ID>
<CardName>GodCard7</CardName>
<CardNameDesc>신 카드 7번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>9</ID>
<CardName>PlayerCard1</CardName>
<CardNameDesc>플레이어 카드 1번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>10</ID>
<CardName>PlayerCard2</CardName>
<CardNameDesc>플레이어 카드 2번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>11</ID>
<CardName>GoblinChildMinder1</CardName>
<CardNameDesc>고블린 보모 카드 1번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>12</ID>
<CardName>GoblinWarriorCard1</CardName>
<CardNameDesc>고블린 전사 카드 1번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>13</ID>
<CardName>GoblinVillageCard1</CardName>
<CardNameDesc>고블린 마을 카드 1번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>14</ID>
<CardName>GoblinVillageCard2</CardName>
<CardNameDesc>고블린 마을 카드 2번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>15</ID>
<CardName>ForestCard1</CardName>
<CardNameDesc>숲 카드 1번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>16</ID>
<CardName>ForestCard2</CardName>
<CardNameDesc>숲 카드 2번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>17</ID>
<CardName>ForestCard3</CardName>
<CardNameDesc>숲 카드 3번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>18</ID>
<CardName>ForestCard4</CardName>
<CardNameDesc>숲 카드 4번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>19</ID>
<CardName>ForestCard5</CardName>
<CardNameDesc>숲 카드 5번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>20</ID>
<CardName>DeepForestCard1</CardName>
<CardNameDesc>깊은 숲 카드 1번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>21</ID>
<CardName>DeepForestCard2</CardName>
<CardNameDesc>깊은 숲 카드 2번</CardNameDesc>
</CardNameTable>
<CardNameTable>
<ID>22</ID>
<CardName>DeepForestCard3</CardName>
<CardNameDesc>깊은 숲 카드 3번</CardNameDesc>
</CardNameTable>
</dataroot>
